### ISSUE TITLE
No Sonos connection

### ISSUE THREAD

**Issue by jrho2** [HydriaOne/subsonic#1]
Sonos cant find the Subsonic server. - It is activated inside subsonic.

Which port do sonos use when it wants to connect to Subsonic? At first i thought it was the 8100 port that was wrong but it didnt help changing it to 4040. And i have also tried to change the Sonos SID - because i already have a Subsonic running on a raspi.

I have also tried to install Airsonic on my omv, but that didnt either work with sonos.

It works on raspi without docker - could the problem be that it, when its installed in a dockercontainer - doesnt have its own "identity" on my network? I wonder whenever some kind of port forward in my router would solve it?

**Comment by HydriaOne** [comment]
Hi jtho2, all the information about sonos is here [http://www.subsonic.org/pages/sonos.jsp](url) 
Sadly i dont use sonos so i cant try it, but exposing the port 4040 should be enough.

`docker run -d -it --restart=always -p 4040:4040 --name=Subsonic -v /mymusic:/var/music -v /opt/subsonic:/var/subsonic hydria/subsonic:latest`
